site_name: backstage
site_description: SourceFuse ARC Backstage platform with GitHub integration, scaffolding templates, and catalog management
repo_url: https://github.com/sourcefuse/backstage
docs_dir: docs

nav:
  - Home: index.md

plugins:
  - techdocs-core
